### ISSUE TITLE
Excessive memory consumption

### ISSUE THREAD

**Issue by gabrielmarcosmag** [robert-chiodi/interface-reconstruction-library#1]
I'm trying to use the ELVIRA reconstruction to compute the surface normals in a Fortran code. I coded it as following:

```
subroutine elvira_vof_normal_loop(f, ga, gb, ncn, dn, nxe, nye, nze)
  use data_global
  use irl_fortran_interface
  implicit none
  !Input
  integer:: ncn(3)
  double precision:: dn(3), ga(3), gb(3)
  double precision, dimension(ncn(1),ncn(2),ncn(3)) :: f , nxe, nye, nze
  !Local
  integer, parameter :: DP = kind(1.0d0)
  integer:: i, j, k, ii, jj, kk, pp, idx(3)
  real(DP) :: distance
  real(DP), dimension(1:3) :: normal, pt1, pt2
  real(DP), dimension(1:4) :: plane
  type(ELVIRANeigh_type) :: elvira_neighborhood
  type(RectCub_type), dimension(-1:1,-1:1,-1:1) :: rectangular_cuboid
  type(PlanarSep_type) :: found_planar_separator

  call new(found_planar_separator)
  call new(elvira_neighborhood)
  call setSize(elvira_neighborhood,27)

  do k = 2, ncn(3)-1
    do j = 2, ncn(2)-1                     
      do i = 2, ncn(1)-1

        if(f(i,j,k) > 0.0d0 .or. f(i,j,k) < 1.0d0)then

          do ii=i-1,i+1; do jj=j-1,j+1; do kk=k-1,k+1
            !!! Min and max points
            idx = [ii,jj,kk]
            do pp = 1,3; pt1(pp) = ga(pp) + (dble(idx(pp))-0.5d0)*dn(pp); end do
            idx = [ii+1,jj+1,kk+1]
            do pp = 1,3; pt2(pp) = ga(pp) + (dble(idx(pp))-0.5d0)*dn(pp); end do

            call new(rectangular_cuboid(ii-i,jj-j,kk-k))
            call construct_2pt(rectangular_cuboid(ii-i,jj-j,kk-k),pt1, pt2)
            call setMember(elvira_neighborhood,rectangular_cuboid(ii-i,jj-j,kk-k), f(ii,jj,kk), ii-i, jj-j, kk-k)

          end do; end do; end do

          call reconstructELVIRA3D(elvira_neighborhood, found_planar_separator)

          plane = getPlane(found_planar_separator,0)

          nxe(i,j,k) = plane(1)
          nye(i,j,k) = plane(2)
          nze(i,j,k) = plane(3)
        end if

      end do
    end do
  end do
  
end subroutine elvira_vof_normal_loop
```

When I increase the number of elements in the grid I observed an excessive memory consumption. There exists any problem with my code or in the library?

**Comment by robert-chiodi** [comment]
Hi @gabrielmarcosmag ,

Thank you for your interest in IRL. The memory issue arises from the line `call new(rectangular_cuboid(ii-i,jj-j,kk-k))`. To fix it, you should call new prior to entering the reconstruction and stencil building loop, such as shown at the end of this post. 

To provide more explanation on why this is the case, it is important to understand what `new` means in this context in the IRL Fortran interface. The Fortran interface is essentially a light wrapper of a C interface that makes calls in the main IRL C++ library. In it, the Fortran version of C++ classes holds pointers (`C_PTR` objects) to the C objects. The calling of `new` here performs an allocation of the IRL C object, after which the `C_PTR` should point to a valid object. The way I typically remember this is that `new` performs a heap allocation in C++, and that is exactly what it is doing here. 

The problem you were seeing therefore happens because you were allocating 27 `RectCub_type` objects per ELVIRA reconstruction, whereas you want to allocate 27 of them once (the size of the stencil) and then reset the object stored through the call the `construct_2pt` as you are doing. Deletion of the memory assigned by new is handled via a Fortran `final` subroutine and will happen automatically when the object goes out of scope.

As a side note, if you compile IRL in debug mode, assertions should catch the attempt to call `new` on an object that is already storing an object (detected by trying to assign a new pointer when the stored pointer is not `nullptr`). This might help you catch a similar problem in the future.

Let me know if this helped.

Cheers,
Robert Chiodi


```
  ! ============================== !
  ! Correct allocation of RectangularCuboid   !
  ! ============================== !
  do k = -1, 1
    do j = -1, 1
      do i = -1, 1
        call new(rectangular_cuboid(i,j,k))
      end do
    end do
  end do

  do k = 2, ncn(3)-1
    do j = 2, ncn(2)-1                     
      do i = 2, ncn(1)-1
        ! Rest of code
```

**Comment by robert-chiodi** [comment]
Hi Gabriel,

I'm going to go ahead and guess this fixed this issue. I hope IRL is going well. If something else comes up from this, feel free to reopen the issue.

Cheers!
